### ISSUE TITLE
[improvement] - Loading on reducer

### ISSUE THREAD

**Issue by edgarbonillag** [DevMcGann/NextDots-CocktailFinder#1]
En el archivo de las actions veo que en este caso, siempre se le manda `true`, entonces aquí puedes dejarle el `true` y quitar el `payload` de donde se despacha la action. (Eso es en este caso solamente, no aplica para todos los casos)

https://github.com/DevMcGann/NextDots-CocktailFinder/blob/9e74c72fc3bae2b9de852e577ad00e25fec6e360/src/store/reducers/DrinkReducer.js#L19

**Comment by DevMcGann** [comment]
Fixed
