### ISSUE TITLE
No spanish

### ISSUE THREAD

**Issue by edgarbonillag** [DevMcGann/NextDots-CocktailFinder#10]
No nombrar componentes ni variables en español. Todo en inglés.
Corregir esto aquí y en otros archivos donde se presenta.

https://github.com/DevMcGann/NextDots-CocktailFinder/blob/9e74c72fc3bae2b9de852e577ad00e25fec6e360/src/screens/SearchScreen/index.js#L73

**Comment by DevMcGann** [comment]
Done
