### ISSUE TITLE
Delete this

### ISSUE THREAD

**Issue by edgarbonillag** [DevMcGann/NextDots-CocktailFinder#11]
Si no se usa, simplemente borrarlo.
TIP: Si fuera super importante como alguna aclaración de alta relevancia en un función o algo así, se puede dejar un comment, pero igual hay que escribirlo en inglés

https://github.com/DevMcGann/NextDots-CocktailFinder/blob/9e74c72fc3bae2b9de852e577ad00e25fec6e360/src/screens/HomeScreen/styles.js#L34

**Comment by DevMcGann** [comment]
Fixed
