### ISSUE TITLE
[improvement] - prettier props

### ISSUE THREAD

**Issue by edgarbonillag** [DevMcGann/NextDots-CocktailFinder#12]
Se puede escribir mejor así
`const searchButton = ({ onPress, text }) => { `

PD: Recordar no usar `snake_case`

https://github.com/DevMcGann/NextDots-CocktailFinder/blob/9e74c72fc3bae2b9de852e577ad00e25fec6e360/src/components/Buttons/Search_Button/index.js#L6

**Comment by DevMcGann** [comment]
Fixed
