### ISSUE TITLE
Import components from index

### ISSUE THREAD

**Issue by edgarbonillag** [DevMcGann/NextDots-CocktailFinder#13]
En general hacer lo siguiente, doy el ejemplo para la carpeta de components

```
components/
  Header/
    index.js
    Header.js
    styles.ts
: 
:
  index.js
```

En el archivo `index.js` de cada componente iría algo como así:
`export { default } from './Header';`

Y en el archivo `index.js` de la carpeta `Components` iría algo así:
```
export { default as Header } from './Header;
: 
:
```

Y cuando tengas que llamar a un componente en una screen sería algo como:
`import { Header }  from '../components'`

**Comment by DevMcGann** [comment]
Fixed
