### ISSUE TITLE
Requiring cycle

### ISSUE THREAD

**Issue by edgarbonillag** [DevMcGann/NextDots-CocktailFinder#15]
Importar así genera requiring cycles. Esto sucede cuando desde una carpeta principal (en este caso `components`) sin importar el grado de profundidad, importas otro archivo/componente/etc desde el index de esa carpeta.
En este caso es mejor importar directamente el componente desde su carpeta propia.
`import CancelButton from '../Buttons/CancelButton';
`
Así mismo, revisa en el archivo `ListOfDrinks.js`

https://github.com/DevMcGann/NextDots-CocktailFinder/blob/3b69def3baecb3d32b2dcea502b2e642563fe155/src/components/Header/Header.js#L6

**Comment by DevMcGann** [comment]
Fixed
