### ISSUE TITLE
Save only the necessary data

### ISSUE THREAD

**Issue by edgarbonillag** [DevMcGann/NextDots-CocktailFinder#4]
Lo ideal sería guardar sólo los datos necesarios en `drinks`.
Sucede que desde la API cada drink llega con un montón de propiedades, pero para este caso sólo se necesitan 3. Entonces guardar que `drinks` sea un array donde cada drink tenga sólo las 3 propiedades necesarias.

https://github.com/DevMcGann/NextDots-CocktailFinder/blob/9e74c72fc3bae2b9de852e577ad00e25fec6e360/src/store/actions/DrinksActions.js#L16

**Comment by DevMcGann** [comment]
Fixed
