### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by edgarbonillag** [DevMcGann/NextDots-CocktailFinder#5]
Le estás mandando el mensaje de error a esta función, pero de hecho la función no está programada para recibir ningún parámetro y no se está haciendo nada con eso.

https://github.com/DevMcGann/NextDots-CocktailFinder/blob/9e74c72fc3bae2b9de852e577ad00e25fec6e360/src/store/actions/DrinksActions.js#L20

**Comment by DevMcGann** [comment]
Fixed
