### ISSUE TITLE
Store error message

### ISSUE THREAD

**Issue by edgarbonillag** [DevMcGann/NextDots-CocktailFinder#6]
Ideal sería guardar el mensaje de error y no un booleano. Luego, en la screen se puede preguntar si el mensaje de error existe (o no es una string vacía). La función lógica es como la misma, pero la diferencia es que queda el mensaje de error a la mano si se necesita

https://github.com/DevMcGann/NextDots-CocktailFinder/blob/9e74c72fc3bae2b9de852e577ad00e25fec6e360/src/store/reducers/DrinkReducer.js#L30

**Comment by DevMcGann** [comment]
Done
