### ISSUE TITLE
Fix all eslint errors

### ISSUE THREAD

**Issue by edgarbonillag** [DevMcGann/NextDots-CocktailFinder#7]
Arreglar todo lo que se requiera para que no haya necesidad de deshabilitar todas estas cosas de eslint.
EDIT: Veo que no sólo pasa en este archivo. Corrgir todos los archivos donde se presente.

https://github.com/DevMcGann/NextDots-CocktailFinder/blob/9e74c72fc3bae2b9de852e577ad00e25fec6e360/src/screens/SearchScreen/index.js#L1

**Comment by DevMcGann** [comment]
Fixed all
