### ISSUE TITLE
Don't use snake_case

### ISSUE THREAD

**Issue by edgarbonillag** [DevMcGann/NextDots-CocktailFinder#9]
Evitar al máximo nombrar funciones o variables (a excepción de los action types) usando `snake_case` . Usar siempre `camelCase`.
Corregir eso aquí y en todos los demás archivos donde se presente

https://github.com/DevMcGann/NextDots-CocktailFinder/blob/9e74c72fc3bae2b9de852e577ad00e25fec6e360/src/screens/SearchScreen/index.js#L41

**Comment by DevMcGann** [comment]
Done
